import { useTranslations } from "next-intl";
import React from "react";
import { Screen } from "@/components/screen";

export const metadata = {
  title: "Website",
  description: "Generated by Obada.Kahlous",
};

export default function Home() {
  const t = useTranslations("Index");

  return <Screen> {t('title')} </Screen>;
}
